In [1]:
import numpy as np
import torch

a = torch.arange(6., 12.)
torch.reshape(a, (3, 2))

tensor([[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [2]:
from torch.utils.data import Dataset, DataLoader

class MinimalDataset(Dataset):
    def __init__(self):
        a = torch.arange(4., dtype=torch.float)
        self.a = torch.reshape(a, (2, 2))
        b = torch.arange(6., 12.)
        self.b = torch.reshape(b, (3, 2))

    def __len__(self):
        return 10000
    
    def __getitem__(self, idx):
        input = torch.randint(0, 100, size=(2,), dtype=torch.float)
        x = self.a.matmul(input)
        y = self.b.matmul(input) < 900
        y_bool = 0#torch.logical_or(torch.logical_and(y[0], y[1]), torch.logical_and(torch.logical_not(y[0]), y[2]))
        print(x, x[0]<50)
        return x, x[0]<50

In [3]:
trainloader = torch.utils.data.DataLoader(MinimalDataset(), batch_size=32)
for data in trainloader:
    break

tensor([ 37., 215.]) tensor(True)
tensor([ 73., 243.]) tensor(False)
tensor([ 70., 404.]) tensor(False)
tensor([ 22., 202.]) tensor(True)
tensor([ 33., 281.]) tensor(True)
tensor([ 90., 290.]) tensor(False)
tensor([ 98., 482.]) tensor(False)
tensor([  1., 129.]) tensor(True)
tensor([ 30., 190.]) tensor(True)
tensor([ 8., 84.]) tensor(True)
tensor([ 91., 457.]) tensor(False)
tensor([ 66., 250.]) tensor(False)
tensor([14., 46.]) tensor(True)
tensor([ 56., 296.]) tensor(False)
tensor([ 58., 288.]) tensor(False)
tensor([ 83., 403.]) tensor(False)
tensor([ 50., 236.]) tensor(False)
tensor([ 36., 128.]) tensor(True)
tensor([ 79., 353.]) tensor(False)
tensor([ 72., 368.]) tensor(False)
tensor([ 13., 199.]) tensor(True)
tensor([ 31., 157.]) tensor(True)
tensor([ 94., 336.]) tensor(False)
tensor([  2., 116.]) tensor(True)
tensor([ 84., 292.]) tensor(False)
tensor([ 83., 443.]) tensor(False)
tensor([ 36., 208.]) tensor(True)
tensor([ 78., 234.]) tensor(False)
tensor([ 98., 420.]) tensor(False)
t

In [4]:
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(2, 100, bias = True)
        self.l2 = nn.Linear(100, 100, bias = True)
        self.l3 = nn.Linear(100, 100, bias = True)
        self.l4 = nn.Linear(100, 100, bias = True)
        self.l5 = nn.Linear(100, 100, bias = True)
        self.l6 = nn.Linear(100, 3, bias = True)
    
    def forward(self, x):
        m = nn.Sigmoid()
        x = self.l1(m(x))
        x = self.l2(m(x))
        x = self.l3(m(x))
        x = self.l4(m(x))
        x = self.l5(m(x))
        x = self.l6(m(x))
        x = nn.Softmax(dim=1)(x)
        return x

In [5]:
import numpy as np
import torch.optim as optim
criterion = nn.CrossEntropyLoss() #nn.MSELoss()
model = Net()
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
train_running_loss = 0
train_running_correct = 0

for i, (data, target) in enumerate(trainloader):
    optimizer.zero_grad()
    output = model(data)
    loss = criterion(output, target.long())# + block_reg
    train_running_loss += loss.item()
    _, preds = torch.max(output.data, 1)
    train_running_correct += (preds == target).sum().item()
    loss.backward()
    optimizer.step()
    print((preds == target).sum().item())

train_loss = train_running_loss/len(trainloader.dataset)
train_accuracy = 100. * train_running_correct/len(trainloader.dataset)
print(f'Train Loss: {train_loss:.4f}, Train Acc: {train_accuracy:.2f}')

tensor([ 51., 349.]) tensor(False)
tensor([ 68., 220.]) tensor(False)
tensor([ 49., 277.]) tensor(True)
tensor([ 12., 186.]) tensor(True)
tensor([ 2., 40.]) tensor(True)
tensor([ 19., 173.]) tensor(True)
tensor([ 21., 229.]) tensor(True)
tensor([ 81., 299.]) tensor(False)
tensor([ 33., 187.]) tensor(True)
tensor([ 29., 169.]) tensor(True)
tensor([ 35., 297.]) tensor(True)
tensor([ 63., 307.]) tensor(False)
tensor([ 71., 223.]) tensor(False)
tensor([25., 97.]) tensor(True)
tensor([ 27., 119.]) tensor(True)
tensor([ 76., 398.]) tensor(False)
tensor([ 55., 295.]) tensor(False)
tensor([ 17., 227.]) tensor(True)
tensor([13., 69.]) tensor(True)
tensor([ 68., 324.]) tensor(False)
tensor([ 88., 298.]) tensor(False)
tensor([  1., 191.]) tensor(True)
tensor([ 69., 361.]) tensor(False)
tensor([ 75., 395.]) tensor(False)
tensor([ 42., 216.]) tensor(True)
tensor([ 90., 408.]) tensor(False)
tensor([ 13., 145.]) tensor(True)
tensor([ 26., 168.]) tensor(True)
tensor([16., 78.]) tensor(True)
tensor([ 8

tensor([ 31., 209.]) tensor(True)
tensor([ 77., 311.]) tensor(False)
tensor([ 49., 345.]) tensor(True)
tensor([ 49., 167.]) tensor(True)
15
tensor([ 84., 314.]) tensor(False)
tensor([  5., 127.]) tensor(True)
tensor([ 36., 234.]) tensor(True)
tensor([ 24., 244.]) tensor(True)
tensor([ 84., 292.]) tensor(False)
tensor([ 58., 318.]) tensor(False)
tensor([ 82., 322.]) tensor(False)
tensor([ 85., 379.]) tensor(False)
tensor([  4., 200.]) tensor(True)
tensor([ 93., 333.]) tensor(False)
tensor([ 56., 212.]) tensor(False)
tensor([ 70., 248.]) tensor(False)
tensor([ 91., 397.]) tensor(False)
tensor([ 43., 307.]) tensor(True)
tensor([ 5., 35.]) tensor(True)
tensor([ 6., 58.]) tensor(True)
tensor([ 41., 215.]) tensor(True)
tensor([ 88., 410.]) tensor(False)
tensor([ 50., 244.]) tensor(False)
tensor([ 52., 254.]) tensor(False)
tensor([ 38., 200.]) tensor(True)
tensor([ 91., 369.]) tensor(False)
tensor([ 43., 203.]) tensor(True)
tensor([ 4., 34.]) tensor(True)
tensor([ 77., 349.]) tensor(False)
te

tensor([ 34., 164.]) tensor(True)
tensor([ 96., 296.]) tensor(False)
tensor([ 41., 159.]) tensor(True)
tensor([ 83., 445.]) tensor(False)
tensor([ 41., 261.]) tensor(True)
tensor([ 8., 62.]) tensor(True)
tensor([ 95., 305.]) tensor(False)
tensor([ 71., 303.]) tensor(False)
tensor([17., 97.]) tensor(True)
tensor([23., 99.]) tensor(True)
tensor([ 81., 423.]) tensor(False)
tensor([ 71., 291.]) tensor(False)
tensor([ 68., 342.]) tensor(False)
tensor([ 61., 339.]) tensor(False)
tensor([ 47., 197.]) tensor(True)
tensor([ 73., 365.]) tensor(False)
tensor([ 13., 219.]) tensor(True)
19
tensor([ 70., 402.]) tensor(False)
tensor([ 83., 327.]) tensor(False)
tensor([ 54., 270.]) tensor(False)
tensor([ 29., 141.]) tensor(True)
tensor([ 98., 490.]) tensor(False)
tensor([ 88., 402.]) tensor(False)
tensor([ 65., 325.]) tensor(False)
tensor([ 18., 224.]) tensor(True)
tensor([ 73., 339.]) tensor(False)
tensor([ 84., 280.]) tensor(False)
tensor([ 59., 273.]) tensor(False)
tensor([ 25., 261.]) tensor(True)

tensor([ 70., 250.]) tensor(False)
tensor([ 68., 394.]) tensor(False)
tensor([  8., 110.]) tensor(True)
tensor([ 60., 196.]) tensor(False)
tensor([ 62., 322.]) tensor(False)
tensor([ 81., 275.]) tensor(False)
tensor([ 5., 25.]) tensor(True)
tensor([ 17., 175.]) tensor(True)
tensor([  8., 100.]) tensor(True)
tensor([ 16., 162.]) tensor(True)
tensor([ 45., 303.]) tensor(True)
14
tensor([ 43., 307.]) tensor(True)
tensor([  7., 163.]) tensor(True)
tensor([ 27., 229.]) tensor(True)
tensor([  8., 178.]) tensor(True)
tensor([ 53., 161.]) tensor(False)
tensor([ 47., 243.]) tensor(True)
tensor([ 39., 207.]) tensor(True)
tensor([ 34., 140.]) tensor(True)
tensor([ 63., 205.]) tensor(False)
tensor([ 3., 61.]) tensor(True)
tensor([ 73., 239.]) tensor(False)
tensor([ 81., 271.]) tensor(False)
tensor([ 25., 135.]) tensor(True)
tensor([ 32., 134.]) tensor(True)
tensor([ 97., 361.]) tensor(False)
tensor([ 36., 182.]) tensor(True)
tensor([ 18., 156.]) tensor(True)
tensor([ 34., 264.]) tensor(True)
tenso

tensor([ 71., 347.]) tensor(False)
tensor([ 90., 376.]) tensor(False)
tensor([  2., 104.]) tensor(True)
tensor([ 71., 311.]) tensor(False)
tensor([ 78., 278.]) tensor(False)
tensor([ 13., 147.]) tensor(True)
tensor([ 14., 152.]) tensor(True)
tensor([ 59., 183.]) tensor(False)
tensor([ 82., 444.]) tensor(False)
tensor([ 66., 292.]) tensor(False)
tensor([ 43., 169.]) tensor(True)
tensor([ 96., 476.]) tensor(False)
tensor([ 47., 211.]) tensor(True)
tensor([ 74., 226.]) tensor(False)
tensor([ 16., 230.]) tensor(True)
tensor([ 99., 335.]) tensor(False)
tensor([ 18., 120.]) tensor(True)
tensor([ 69., 337.]) tensor(False)
tensor([ 97., 373.]) tensor(False)
tensor([ 46., 236.]) tensor(True)
tensor([ 44., 132.]) tensor(True)
tensor([ 7., 91.]) tensor(True)
tensor([ 68., 398.]) tensor(False)
14
tensor([  2., 204.]) tensor(True)
tensor([ 70., 262.]) tensor(False)
tensor([ 45., 141.]) tensor(True)
tensor([ 13., 105.]) tensor(True)
tensor([  9., 129.]) tensor(True)
tensor([ 15., 191.]) tensor(True)

tensor([ 95., 433.]) tensor(False)
tensor([ 6., 58.]) tensor(True)
tensor([ 85., 415.]) tensor(False)
tensor([ 13., 187.]) tensor(True)
tensor([ 64., 222.]) tensor(False)
tensor([ 76., 248.]) tensor(False)
tensor([ 25., 191.]) tensor(True)
tensor([ 45., 211.]) tensor(True)
tensor([ 99., 341.]) tensor(False)
tensor([ 49., 285.]) tensor(True)
tensor([ 3., 51.]) tensor(True)
tensor([ 32., 244.]) tensor(True)
tensor([ 63., 361.]) tensor(False)
tensor([ 9., 67.]) tensor(True)
tensor([ 44., 150.]) tensor(True)
tensor([ 28., 230.]) tensor(True)
18
tensor([ 46., 174.]) tensor(True)
tensor([ 20., 160.]) tensor(True)
tensor([ 29., 229.]) tensor(True)
tensor([ 73., 239.]) tensor(False)
tensor([ 70., 278.]) tensor(False)
tensor([ 44., 144.]) tensor(True)
tensor([ 82., 292.]) tensor(False)
tensor([ 54., 332.]) tensor(False)
tensor([ 83., 351.]) tensor(False)
tensor([ 46., 154.]) tensor(True)
tensor([ 34., 126.]) tensor(True)
tensor([ 22., 108.]) tensor(True)
tensor([ 74., 320.]) tensor(False)
tenso

tensor([ 75., 375.]) tensor(False)
tensor([ 3., 57.]) tensor(True)
tensor([ 26., 240.]) tensor(True)
tensor([ 94., 344.]) tensor(False)
tensor([ 42., 242.]) tensor(True)
tensor([ 3., 93.]) tensor(True)
tensor([ 92., 450.]) tensor(False)
tensor([ 92., 338.]) tensor(False)
16
tensor([ 87., 271.]) tensor(False)
tensor([ 66., 336.]) tensor(False)
tensor([ 25., 191.]) tensor(True)
tensor([ 80., 306.]) tensor(False)
tensor([ 13., 229.]) tensor(True)
tensor([ 46., 212.]) tensor(True)
tensor([ 20., 166.]) tensor(True)
tensor([ 60., 188.]) tensor(False)
tensor([ 49., 209.]) tensor(True)
tensor([ 63., 259.]) tensor(False)
tensor([ 62., 206.]) tensor(False)
tensor([ 1., 23.]) tensor(True)
tensor([ 36., 112.]) tensor(True)
tensor([ 91., 307.]) tensor(False)
tensor([ 77., 339.]) tensor(False)
tensor([ 76., 372.]) tensor(False)
tensor([ 37., 225.]) tensor(True)
tensor([ 53., 323.]) tensor(False)
tensor([ 97., 379.]) tensor(False)
tensor([ 95., 341.]) tensor(False)
tensor([ 75., 375.]) tensor(False)


tensor([ 18., 208.]) tensor(True)
tensor([ 76., 354.]) tensor(False)
tensor([ 37., 263.]) tensor(True)
tensor([10., 46.]) tensor(True)
tensor([  9., 201.]) tensor(True)
tensor([ 22., 234.]) tensor(True)
tensor([ 89., 453.]) tensor(False)
tensor([ 71., 363.]) tensor(False)
tensor([ 91., 291.]) tensor(False)
tensor([ 53., 217.]) tensor(False)
tensor([ 16., 206.]) tensor(True)
tensor([ 88., 332.]) tensor(False)
tensor([ 92., 322.]) tensor(False)
tensor([ 93., 347.]) tensor(False)
tensor([ 65., 315.]) tensor(False)
tensor([ 2., 64.]) tensor(True)
tensor([ 2., 26.]) tensor(True)
tensor([ 40., 252.]) tensor(True)
tensor([  4., 120.]) tensor(True)
tensor([  5., 209.]) tensor(True)
tensor([ 55., 203.]) tensor(False)
tensor([ 96., 424.]) tensor(False)
tensor([ 79., 289.]) tensor(False)
tensor([  0., 166.]) tensor(True)
tensor([ 58., 180.]) tensor(False)
14
tensor([ 37., 285.]) tensor(True)
tensor([ 74., 244.]) tensor(False)
tensor([ 79., 241.]) tensor(False)
tensor([ 76., 420.]) tensor(False)
t

tensor([ 57., 181.]) tensor(False)
tensor([ 38., 248.]) tensor(True)
tensor([ 45., 217.]) tensor(True)
tensor([ 67., 297.]) tensor(False)
tensor([  6., 126.]) tensor(True)
tensor([ 76., 248.]) tensor(False)
tensor([ 87., 327.]) tensor(False)
tensor([ 68., 362.]) tensor(False)
tensor([ 65., 343.]) tensor(False)
tensor([ 38., 146.]) tensor(True)
tensor([ 65., 279.]) tensor(False)
tensor([ 48., 304.]) tensor(True)
tensor([ 12., 136.]) tensor(True)
tensor([ 75., 225.]) tensor(False)
tensor([ 65., 303.]) tensor(False)
tensor([ 44., 146.]) tensor(True)
18
tensor([ 51., 187.]) tensor(False)
tensor([ 48., 146.]) tensor(True)
tensor([10., 36.]) tensor(True)
tensor([ 71., 247.]) tensor(False)
tensor([ 8., 88.]) tensor(True)
tensor([ 68., 380.]) tensor(False)
tensor([ 58., 282.]) tensor(False)
tensor([ 99., 305.]) tensor(False)
tensor([  3., 137.]) tensor(True)
tensor([ 66., 208.]) tensor(False)
tensor([  0., 108.]) tensor(True)
tensor([ 27., 175.]) tensor(True)
tensor([ 68., 314.]) tensor(False)

tensor([ 83., 339.]) tensor(False)
tensor([ 94., 308.]) tensor(False)
tensor([ 52., 212.]) tensor(False)
tensor([ 71., 275.]) tensor(False)
tensor([ 12., 216.]) tensor(True)
tensor([ 67., 225.]) tensor(False)
tensor([ 49., 189.]) tensor(True)
tensor([ 43., 171.]) tensor(True)
tensor([ 10., 222.]) tensor(True)
tensor([ 29., 195.]) tensor(True)
tensor([ 55., 363.]) tensor(False)
tensor([ 77., 313.]) tensor(False)
tensor([ 67., 293.]) tensor(False)
tensor([  3., 197.]) tensor(True)
tensor([ 70., 278.]) tensor(False)
tensor([ 91., 449.]) tensor(False)
tensor([ 17., 169.]) tensor(True)
tensor([ 32., 158.]) tensor(True)
tensor([ 94., 408.]) tensor(False)
tensor([ 62., 304.]) tensor(False)
tensor([ 89., 359.]) tensor(False)
tensor([ 89., 275.]) tensor(False)
17
tensor([ 89., 345.]) tensor(False)
tensor([ 0., 70.]) tensor(True)
tensor([ 29., 145.]) tensor(True)
tensor([ 57., 327.]) tensor(False)
tensor([ 43., 207.]) tensor(True)
tensor([ 52., 238.]) tensor(False)
tensor([ 74., 362.]) tensor(Fa

tensor([ 53., 209.]) tensor(False)
tensor([10., 40.]) tensor(True)
tensor([ 77., 315.]) tensor(False)
tensor([ 94., 428.]) tensor(False)
tensor([ 80., 292.]) tensor(False)
tensor([12., 64.]) tensor(True)
tensor([ 48., 176.]) tensor(True)
tensor([ 36., 292.]) tensor(True)
tensor([ 50., 160.]) tensor(False)
tensor([ 36., 246.]) tensor(True)
tensor([ 62., 364.]) tensor(False)
tensor([  7., 173.]) tensor(True)
tensor([ 24., 140.]) tensor(True)
tensor([ 25., 231.]) tensor(True)
tensor([ 27., 225.]) tensor(True)
tensor([ 85., 303.]) tensor(False)
17
tensor([ 2., 12.]) tensor(True)
tensor([  7., 163.]) tensor(True)
tensor([ 47., 227.]) tensor(True)
tensor([ 91., 427.]) tensor(False)
tensor([ 43., 129.]) tensor(True)
tensor([ 54., 276.]) tensor(False)
tensor([ 62., 214.]) tensor(False)
tensor([  9., 135.]) tensor(True)
tensor([ 53., 267.]) tensor(False)
tensor([ 73., 397.]) tensor(False)
tensor([ 45., 219.]) tensor(True)
tensor([ 58., 302.]) tensor(False)
tensor([ 12., 230.]) tensor(True)
tens

tensor([ 93., 305.]) tensor(False)
tensor([ 42., 172.]) tensor(True)
tensor([ 87., 363.]) tensor(False)
tensor([ 85., 441.]) tensor(False)
tensor([ 92., 474.]) tensor(False)
tensor([  6., 182.]) tensor(True)
tensor([ 31., 219.]) tensor(True)
tensor([ 40., 302.]) tensor(True)
tensor([ 65., 223.]) tensor(False)
tensor([ 18., 248.]) tensor(True)
tensor([ 64., 246.]) tensor(False)
tensor([ 4., 80.]) tensor(True)
tensor([ 33., 283.]) tensor(True)
tensor([ 37., 305.]) tensor(True)
tensor([  3., 171.]) tensor(True)
tensor([ 46., 246.]) tensor(True)
tensor([ 68., 226.]) tensor(False)
tensor([ 96., 324.]) tensor(False)
tensor([ 58., 214.]) tensor(False)
tensor([ 30., 182.]) tensor(True)
tensor([  9., 209.]) tensor(True)
tensor([ 20., 120.]) tensor(True)
tensor([ 70., 392.]) tensor(False)
tensor([ 86., 398.]) tensor(False)
tensor([ 39., 239.]) tensor(True)
tensor([ 89., 421.]) tensor(False)
tensor([ 71., 253.]) tensor(False)
tensor([ 87., 349.]) tensor(False)
tensor([ 55., 223.]) tensor(False)
1

tensor([ 66., 304.]) tensor(False)
tensor([ 81., 433.]) tensor(False)
tensor([ 55., 287.]) tensor(False)
tensor([ 24., 182.]) tensor(True)
tensor([ 71., 213.]) tensor(False)
tensor([  3., 207.]) tensor(True)
tensor([ 97., 347.]) tensor(False)
tensor([  3., 149.]) tensor(True)
tensor([ 34., 192.]) tensor(True)
tensor([ 32., 204.]) tensor(True)
tensor([ 72., 276.]) tensor(False)
tensor([ 8., 36.]) tensor(True)
tensor([ 11., 207.]) tensor(True)
tensor([ 63., 371.]) tensor(False)
tensor([ 13., 205.]) tensor(True)
tensor([ 15., 103.]) tensor(True)
tensor([ 99., 465.]) tensor(False)
tensor([ 88., 452.]) tensor(False)
tensor([ 86., 310.]) tensor(False)
tensor([ 81., 249.]) tensor(False)
tensor([ 39., 307.]) tensor(True)
tensor([  6., 188.]) tensor(True)
tensor([ 67., 217.]) tensor(False)
tensor([ 51., 219.]) tensor(False)
tensor([ 77., 417.]) tensor(False)
tensor([ 48., 150.]) tensor(True)
tensor([ 28., 238.]) tensor(True)
tensor([ 98., 486.]) tensor(False)
tensor([ 62., 306.]) tensor(False)


tensor([  2., 182.]) tensor(True)
tensor([ 94., 426.]) tensor(False)
tensor([  0., 192.]) tensor(True)
tensor([ 28., 210.]) tensor(True)
tensor([ 39., 209.]) tensor(True)
tensor([ 79., 429.]) tensor(False)
tensor([ 60., 222.]) tensor(False)
tensor([ 50., 326.]) tensor(False)
tensor([ 87., 273.]) tensor(False)
tensor([ 40., 136.]) tensor(True)
tensor([ 19., 255.]) tensor(True)
tensor([12., 82.]) tensor(True)
tensor([ 40., 156.]) tensor(True)
tensor([ 85., 311.]) tensor(False)
tensor([ 44., 134.]) tensor(True)
tensor([ 45., 319.]) tensor(True)
tensor([ 17., 241.]) tensor(True)
17
tensor([ 40., 306.]) tensor(True)
tensor([ 55., 279.]) tensor(False)
tensor([ 52., 206.]) tensor(False)
tensor([ 14., 106.]) tensor(True)
tensor([ 63., 265.]) tensor(False)
tensor([ 52., 212.]) tensor(False)
tensor([ 62., 224.]) tensor(False)
tensor([ 66., 382.]) tensor(False)
tensor([ 7., 95.]) tensor(True)
tensor([ 51., 153.]) tensor(False)
tensor([ 95., 337.]) tensor(False)
tensor([ 40., 200.]) tensor(True)
t

tensor([ 14., 172.]) tensor(True)
tensor([ 34., 164.]) tensor(True)
tensor([ 78., 412.]) tensor(False)
tensor([ 89., 419.]) tensor(False)
tensor([ 43., 179.]) tensor(True)
tensor([ 78., 302.]) tensor(False)
tensor([ 36., 246.]) tensor(True)
tensor([ 98., 476.]) tensor(False)
tensor([ 31., 289.]) tensor(True)
tensor([ 96., 292.]) tensor(False)
tensor([ 5., 17.]) tensor(True)
tensor([ 29., 129.]) tensor(True)
15
tensor([ 87., 333.]) tensor(False)
tensor([ 89., 331.]) tensor(False)
tensor([ 53., 235.]) tensor(False)
tensor([ 35., 249.]) tensor(True)
tensor([ 62., 222.]) tensor(False)
tensor([ 23., 119.]) tensor(True)
tensor([ 4., 76.]) tensor(True)
tensor([ 82., 426.]) tensor(False)
tensor([ 36., 200.]) tensor(True)
tensor([ 88., 320.]) tensor(False)
tensor([  8., 180.]) tensor(True)
tensor([ 87., 421.]) tensor(False)
tensor([  1., 183.]) tensor(True)
tensor([ 91., 413.]) tensor(False)
tensor([  0., 150.]) tensor(True)
tensor([ 56., 234.]) tensor(False)
tensor([14., 78.]) tensor(True)
ten

tensor([ 18., 208.]) tensor(True)
tensor([ 53., 193.]) tensor(False)
tensor([ 45., 313.]) tensor(True)
tensor([ 34., 192.]) tensor(True)
tensor([ 80., 362.]) tensor(False)
tensor([ 21., 183.]) tensor(True)
tensor([ 47., 297.]) tensor(True)
tensor([ 34., 214.]) tensor(True)
18
tensor([ 39., 249.]) tensor(True)
tensor([ 12., 110.]) tensor(True)
tensor([ 45., 141.]) tensor(True)
tensor([ 96., 296.]) tensor(False)
tensor([ 44., 310.]) tensor(True)
tensor([ 31., 285.]) tensor(True)
tensor([  1., 113.]) tensor(True)
tensor([  2., 182.]) tensor(True)
tensor([ 52., 194.]) tensor(False)
tensor([19., 95.]) tensor(True)
tensor([ 19., 179.]) tensor(True)
tensor([ 87., 389.]) tensor(False)
tensor([ 78., 332.]) tensor(False)
tensor([ 6., 92.]) tensor(True)
tensor([  0., 104.]) tensor(True)
tensor([ 67., 249.]) tensor(False)
tensor([ 54., 218.]) tensor(False)
tensor([ 69., 297.]) tensor(False)
tensor([ 71., 279.]) tensor(False)
tensor([ 29., 241.]) tensor(True)
tensor([ 3., 15.]) tensor(True)
tensor(

21
tensor([ 31., 103.]) tensor(True)
tensor([ 78., 404.]) tensor(False)
tensor([ 14., 138.]) tensor(True)
tensor([ 69., 395.]) tensor(False)
tensor([ 19., 187.]) tensor(True)
tensor([ 20., 162.]) tensor(True)
tensor([ 34., 296.]) tensor(True)
tensor([ 46., 152.]) tensor(True)
tensor([ 78., 426.]) tensor(False)
tensor([ 62., 230.]) tensor(False)
tensor([ 34., 220.]) tensor(True)
tensor([ 31., 261.]) tensor(True)
tensor([ 61., 221.]) tensor(False)
tensor([ 53., 197.]) tensor(False)
tensor([ 60., 314.]) tensor(False)
tensor([ 66., 346.]) tensor(False)
tensor([ 69., 385.]) tensor(False)
tensor([15., 77.]) tensor(True)
tensor([ 13., 157.]) tensor(True)
tensor([ 77., 285.]) tensor(False)
tensor([ 35., 117.]) tensor(True)
tensor([ 29., 139.]) tensor(True)
tensor([ 25., 191.]) tensor(True)
tensor([ 37., 277.]) tensor(True)
tensor([ 70., 318.]) tensor(False)
tensor([ 73., 323.]) tensor(False)
tensor([23., 69.]) tensor(True)
tensor([ 30., 278.]) tensor(True)
tensor([ 73., 339.]) tensor(False)
te

tensor([ 66., 382.]) tensor(False)
tensor([ 10., 172.]) tensor(True)
tensor([ 84., 374.]) tensor(False)
tensor([ 78., 310.]) tensor(False)
tensor([ 66., 246.]) tensor(False)
tensor([ 91., 325.]) tensor(False)
tensor([ 8., 48.]) tensor(True)
tensor([ 65., 377.]) tensor(False)
tensor([ 51., 299.]) tensor(False)
tensor([  8., 204.]) tensor(True)
tensor([ 63., 221.]) tensor(False)
17
tensor([ 86., 258.]) tensor(False)
tensor([ 78., 296.]) tensor(False)
tensor([ 82., 368.]) tensor(False)
tensor([ 37., 267.]) tensor(True)
tensor([ 24., 150.]) tensor(True)
tensor([ 50., 254.]) tensor(False)
tensor([ 61., 353.]) tensor(False)
tensor([ 23., 243.]) tensor(True)
tensor([ 79., 271.]) tensor(False)
tensor([ 15., 205.]) tensor(True)
tensor([19., 65.]) tensor(True)
tensor([ 59., 361.]) tensor(False)
tensor([  7., 213.]) tensor(True)
tensor([ 97., 325.]) tensor(False)
tensor([ 92., 386.]) tensor(False)
tensor([ 57., 341.]) tensor(False)
tensor([ 13., 107.]) tensor(True)
tensor([ 80., 416.]) tensor(Fal

tensor([  0., 170.]) tensor(True)
tensor([ 38., 254.]) tensor(True)
tensor([ 88., 422.]) tensor(False)
tensor([ 64., 208.]) tensor(False)
tensor([ 33., 129.]) tensor(True)
tensor([ 48., 246.]) tensor(True)
15
tensor([ 64., 378.]) tensor(False)
tensor([ 82., 362.]) tensor(False)
tensor([ 89., 313.]) tensor(False)
tensor([ 91., 411.]) tensor(False)
tensor([ 48., 190.]) tensor(True)
tensor([ 52., 270.]) tensor(False)
tensor([ 20., 230.]) tensor(True)
tensor([ 53., 197.]) tensor(False)
tensor([ 86., 342.]) tensor(False)
tensor([ 53., 315.]) tensor(False)
tensor([  6., 126.]) tensor(True)
tensor([ 30., 126.]) tensor(True)
tensor([ 78., 242.]) tensor(False)
tensor([16., 94.]) tensor(True)
tensor([ 26., 134.]) tensor(True)
tensor([ 38., 298.]) tensor(True)
tensor([ 95., 403.]) tensor(False)
tensor([ 25., 195.]) tensor(True)
tensor([ 36., 156.]) tensor(True)
tensor([ 31., 275.]) tensor(True)
tensor([14., 76.]) tensor(True)
tensor([ 70., 344.]) tensor(False)
tensor([ 66., 292.]) tensor(False)
t

tensor([ 59., 287.]) tensor(False)
tensor([ 8., 30.]) tensor(True)
20
tensor([ 24., 108.]) tensor(True)
tensor([ 91., 451.]) tensor(False)
tensor([ 62., 240.]) tensor(False)
tensor([ 17., 127.]) tensor(True)
tensor([ 26., 184.]) tensor(True)
tensor([ 23., 115.]) tensor(True)
tensor([ 93., 299.]) tensor(False)
tensor([ 76., 308.]) tensor(False)
tensor([ 5., 31.]) tensor(True)
tensor([ 31., 233.]) tensor(True)
tensor([ 35., 167.]) tensor(True)
tensor([ 41., 233.]) tensor(True)
tensor([ 27., 117.]) tensor(True)
tensor([ 24., 118.]) tensor(True)
tensor([  3., 189.]) tensor(True)
tensor([ 19., 163.]) tensor(True)
tensor([ 65., 271.]) tensor(False)
tensor([ 44., 214.]) tensor(True)
tensor([  9., 143.]) tensor(True)
tensor([ 2., 80.]) tensor(True)
tensor([ 28., 188.]) tensor(True)
tensor([ 80., 244.]) tensor(False)
tensor([ 93., 389.]) tensor(False)
tensor([ 35., 125.]) tensor(True)
tensor([ 75., 307.]) tensor(False)
tensor([3., 9.]) tensor(True)
tensor([ 21., 195.]) tensor(True)
tensor([ 33.

tensor([ 95., 285.]) tensor(False)
tensor([ 33., 141.]) tensor(True)
tensor([ 56., 280.]) tensor(False)
tensor([ 64., 270.]) tensor(False)
tensor([ 83., 375.]) tensor(False)
tensor([  6., 146.]) tensor(True)
tensor([21., 69.]) tensor(True)
tensor([ 68., 302.]) tensor(False)
tensor([ 72., 230.]) tensor(False)
tensor([ 33., 135.]) tensor(True)
tensor([ 56., 260.]) tensor(False)
tensor([ 79., 333.]) tensor(False)
tensor([ 38., 274.]) tensor(True)
tensor([ 48., 266.]) tensor(True)
tensor([  6., 178.]) tensor(True)
18
tensor([ 70., 296.]) tensor(False)
tensor([ 60., 356.]) tensor(False)
tensor([ 94., 438.]) tensor(False)
tensor([ 36., 136.]) tensor(True)
tensor([ 51., 295.]) tensor(False)
tensor([ 30., 142.]) tensor(True)
tensor([ 9., 97.]) tensor(True)
tensor([  8., 140.]) tensor(True)
tensor([ 11., 133.]) tensor(True)
tensor([ 58., 318.]) tensor(False)
tensor([ 81., 401.]) tensor(False)
tensor([ 22., 148.]) tensor(True)
tensor([ 64., 274.]) tensor(False)
tensor([ 63., 343.]) tensor(False)

tensor([ 90., 302.]) tensor(False)
tensor([ 58., 366.]) tensor(False)
tensor([ 53., 285.]) tensor(False)
tensor([ 59., 191.]) tensor(False)
tensor([ 40., 288.]) tensor(True)
tensor([  8., 146.]) tensor(True)
tensor([ 79., 425.]) tensor(False)
tensor([ 50., 176.]) tensor(False)
tensor([ 56., 272.]) tensor(False)
tensor([ 2., 42.]) tensor(True)
tensor([ 85., 419.]) tensor(False)
tensor([ 88., 322.]) tensor(False)
tensor([ 44., 206.]) tensor(True)
tensor([18., 76.]) tensor(True)
tensor([  3., 165.]) tensor(True)
tensor([ 66., 316.]) tensor(False)
tensor([ 51., 311.]) tensor(False)
tensor([ 30., 266.]) tensor(True)
tensor([ 89., 283.]) tensor(False)
tensor([ 87., 311.]) tensor(False)
tensor([ 46., 218.]) tensor(True)
tensor([ 28., 162.]) tensor(True)
tensor([ 35., 233.]) tensor(True)
tensor([ 80., 320.]) tensor(False)
tensor([13., 47.]) tensor(True)
tensor([ 55., 175.]) tensor(False)
tensor([ 1., 65.]) tensor(True)
tensor([ 27., 139.]) tensor(True)
tensor([ 51., 185.]) tensor(False)
tensor

tensor([ 99., 365.]) tensor(False)
tensor([ 80., 402.]) tensor(False)
tensor([ 58., 222.]) tensor(False)
tensor([ 48., 198.]) tensor(True)
tensor([ 36., 290.]) tensor(True)
tensor([ 77., 297.]) tensor(False)
18
tensor([10., 86.]) tensor(True)
tensor([ 37., 291.]) tensor(True)
tensor([ 66., 218.]) tensor(False)
tensor([ 85., 297.]) tensor(False)
tensor([ 41., 125.]) tensor(True)
tensor([ 41., 189.]) tensor(True)
tensor([ 69., 279.]) tensor(False)
tensor([ 2., 78.]) tensor(True)
tensor([ 62., 278.]) tensor(False)
tensor([ 35., 299.]) tensor(True)
tensor([ 25., 115.]) tensor(True)
tensor([ 88., 428.]) tensor(False)
tensor([ 43., 225.]) tensor(True)
tensor([ 66., 276.]) tensor(False)
tensor([ 23., 227.]) tensor(True)
tensor([ 66., 364.]) tensor(False)
tensor([ 35., 229.]) tensor(True)
tensor([ 67., 353.]) tensor(False)
tensor([ 19., 221.]) tensor(True)
tensor([ 22., 248.]) tensor(True)
tensor([ 16., 124.]) tensor(True)
tensor([ 33., 285.]) tensor(True)
tensor([  8., 140.]) tensor(True)
ten

21
tensor([ 51., 219.]) tensor(False)
tensor([ 33., 285.]) tensor(True)
tensor([ 50., 230.]) tensor(False)
tensor([ 26., 174.]) tensor(True)
tensor([ 68., 266.]) tensor(False)
tensor([ 41., 141.]) tensor(True)
tensor([ 46., 184.]) tensor(True)
tensor([ 70., 228.]) tensor(False)
tensor([ 68., 266.]) tensor(False)
tensor([ 12., 150.]) tensor(True)
tensor([ 76., 386.]) tensor(False)
tensor([ 51., 183.]) tensor(False)
tensor([ 98., 392.]) tensor(False)
tensor([ 78., 234.]) tensor(False)
tensor([ 40., 222.]) tensor(True)
tensor([ 98., 370.]) tensor(False)
tensor([ 50., 298.]) tensor(False)
tensor([  8., 196.]) tensor(True)
tensor([ 63., 235.]) tensor(False)
tensor([ 93., 331.]) tensor(False)
tensor([ 3., 79.]) tensor(True)
tensor([ 31., 277.]) tensor(True)
tensor([ 33., 111.]) tensor(True)
tensor([ 3., 33.]) tensor(True)
tensor([ 36., 246.]) tensor(True)
tensor([ 80., 312.]) tensor(False)
tensor([ 65., 219.]) tensor(False)
tensor([ 24., 108.]) tensor(True)
tensor([ 61., 297.]) tensor(False)

tensor([ 35., 261.]) tensor(True)
tensor([ 32., 170.]) tensor(True)
tensor([ 66., 254.]) tensor(False)
tensor([ 67., 275.]) tensor(False)
tensor([ 18., 140.]) tensor(True)
tensor([ 24., 110.]) tensor(True)
tensor([ 45., 293.]) tensor(True)
12
tensor([ 10., 226.]) tensor(True)
tensor([ 55., 351.]) tensor(False)
tensor([ 10., 202.]) tensor(True)
tensor([ 7., 35.]) tensor(True)
tensor([ 48., 242.]) tensor(True)
tensor([ 63., 363.]) tensor(False)
tensor([ 73., 259.]) tensor(False)
tensor([ 77., 351.]) tensor(False)
tensor([ 76., 260.]) tensor(False)
tensor([ 54., 348.]) tensor(False)
tensor([ 81., 347.]) tensor(False)
tensor([ 65., 385.]) tensor(False)
tensor([ 53., 267.]) tensor(False)
tensor([ 81., 243.]) tensor(False)
tensor([ 72., 364.]) tensor(False)
tensor([  2., 148.]) tensor(True)
tensor([16., 94.]) tensor(True)
tensor([ 50., 178.]) tensor(False)
tensor([ 10., 224.]) tensor(True)
tensor([ 93., 281.]) tensor(False)
tensor([  5., 183.]) tensor(True)
tensor([ 66., 210.]) tensor(False)

tensor([11., 77.]) tensor(True)
tensor([ 30., 220.]) tensor(True)
tensor([ 1., 33.]) tensor(True)
tensor([ 23., 253.]) tensor(True)
tensor([ 15., 243.]) tensor(True)
tensor([  1., 103.]) tensor(True)
tensor([  8., 134.]) tensor(True)
12
tensor([ 92., 438.]) tensor(False)
tensor([20., 98.]) tensor(True)
tensor([ 26., 262.]) tensor(True)
tensor([ 35., 285.]) tensor(True)
tensor([ 45., 247.]) tensor(True)
tensor([ 94., 436.]) tensor(False)
tensor([ 91., 325.]) tensor(False)
tensor([ 74., 410.]) tensor(False)
tensor([ 88., 422.]) tensor(False)
tensor([ 46., 144.]) tensor(True)
tensor([ 22., 120.]) tensor(True)
tensor([ 90., 402.]) tensor(False)
tensor([ 34., 266.]) tensor(True)
tensor([10., 44.]) tensor(True)
tensor([ 32., 276.]) tensor(True)
tensor([ 7., 31.]) tensor(True)
tensor([ 94., 456.]) tensor(False)
tensor([29., 87.]) tensor(True)
tensor([28., 96.]) tensor(True)
tensor([ 70., 354.]) tensor(False)
tensor([ 32., 132.]) tensor(True)
tensor([ 62., 374.]) tensor(False)
tensor([ 20., 24

tensor([ 22., 128.]) tensor(True)
tensor([ 97., 437.]) tensor(False)
tensor([  4., 118.]) tensor(True)
tensor([ 43., 265.]) tensor(True)
tensor([ 6., 44.]) tensor(True)
tensor([11., 81.]) tensor(True)
tensor([  2., 106.]) tensor(True)
tensor([ 17., 171.]) tensor(True)
tensor([ 50., 252.]) tensor(False)
tensor([ 73., 219.]) tensor(False)
tensor([ 82., 292.]) tensor(False)
tensor([ 11., 189.]) tensor(True)
tensor([ 55., 351.]) tensor(False)
tensor([ 41., 139.]) tensor(True)
tensor([ 19., 101.]) tensor(True)
tensor([ 31., 231.]) tensor(True)
tensor([ 46., 140.]) tensor(True)
tensor([ 21., 233.]) tensor(True)
tensor([ 97., 409.]) tensor(False)
tensor([ 23., 253.]) tensor(True)
tensor([ 6., 80.]) tensor(True)
22
tensor([ 21., 199.]) tensor(True)
tensor([ 80., 318.]) tensor(False)
tensor([ 22., 112.]) tensor(True)
tensor([ 18., 106.]) tensor(True)
tensor([ 62., 338.]) tensor(False)
tensor([ 94., 338.]) tensor(False)
tensor([ 79., 419.]) tensor(False)
tensor([ 80., 416.]) tensor(False)
tensor

tensor([14., 92.]) tensor(True)
tensor([ 11., 179.]) tensor(True)
tensor([ 25., 229.]) tensor(True)
tensor([ 40., 234.]) tensor(True)
tensor([ 65., 379.]) tensor(False)
tensor([ 90., 440.]) tensor(False)
tensor([ 26., 260.]) tensor(True)
tensor([ 74., 354.]) tensor(False)
tensor([ 58., 250.]) tensor(False)
tensor([ 2., 30.]) tensor(True)
12
tensor([ 59., 297.]) tensor(False)
tensor([ 76., 400.]) tensor(False)
tensor([ 40., 210.]) tensor(True)
tensor([ 70., 314.]) tensor(False)
tensor([ 33., 211.]) tensor(True)
tensor([ 51., 307.]) tensor(False)
tensor([  6., 206.]) tensor(True)
tensor([ 54., 278.]) tensor(False)
tensor([ 73., 261.]) tensor(False)
tensor([18., 94.]) tensor(True)
tensor([ 3., 63.]) tensor(True)
tensor([ 43., 151.]) tensor(True)
tensor([ 56., 286.]) tensor(False)
tensor([ 87., 375.]) tensor(False)
tensor([ 92., 364.]) tensor(False)
tensor([ 38., 152.]) tensor(True)
tensor([ 85., 339.]) tensor(False)
tensor([ 39., 173.]) tensor(True)
tensor([ 40., 128.]) tensor(True)
tenso

tensor([ 43., 327.]) tensor(True)
tensor([  5., 137.]) tensor(True)
tensor([ 44., 264.]) tensor(True)
tensor([ 46., 248.]) tensor(True)
tensor([ 99., 407.]) tensor(False)
tensor([ 50., 258.]) tensor(False)
tensor([ 35., 197.]) tensor(True)
tensor([ 54., 360.]) tensor(False)
tensor([ 57., 309.]) tensor(False)
tensor([ 93., 467.]) tensor(False)
15
tensor([ 95., 287.]) tensor(False)
tensor([ 99., 363.]) tensor(False)
tensor([ 58., 268.]) tensor(False)
tensor([ 60., 356.]) tensor(False)
tensor([ 73., 413.]) tensor(False)
tensor([ 62., 250.]) tensor(False)
tensor([ 89., 363.]) tensor(False)
tensor([ 86., 374.]) tensor(False)
tensor([20., 90.]) tensor(True)
tensor([ 93., 423.]) tensor(False)
tensor([ 77., 375.]) tensor(False)
tensor([ 66., 272.]) tensor(False)
tensor([ 40., 214.]) tensor(True)
tensor([ 72., 376.]) tensor(False)
tensor([ 37., 273.]) tensor(True)
tensor([ 37., 185.]) tensor(True)
tensor([ 87., 459.]) tensor(False)
tensor([ 12., 122.]) tensor(True)
tensor([ 94., 424.]) tensor(F

tensor([ 24., 194.]) tensor(True)
tensor([ 33., 135.]) tensor(True)
tensor([ 75., 249.]) tensor(False)
tensor([ 89., 269.]) tensor(False)
tensor([ 84., 422.]) tensor(False)
tensor([ 75., 255.]) tensor(False)
tensor([ 85., 269.]) tensor(False)
tensor([ 8., 46.]) tensor(True)
tensor([ 63., 283.]) tensor(False)
tensor([ 95., 377.]) tensor(False)
tensor([  5., 213.]) tensor(True)
tensor([ 40., 280.]) tensor(True)
tensor([ 9., 33.]) tensor(True)
tensor([ 36., 186.]) tensor(True)
tensor([ 17., 209.]) tensor(True)
tensor([ 91., 329.]) tensor(False)
tensor([ 28., 156.]) tensor(True)
tensor([  1., 199.]) tensor(True)
tensor([ 69., 313.]) tensor(False)
tensor([ 96., 394.]) tensor(False)
tensor([ 47., 221.]) tensor(True)
tensor([ 27., 205.]) tensor(True)
tensor([ 65., 307.]) tensor(False)
tensor([ 90., 354.]) tensor(False)
tensor([ 74., 328.]) tensor(False)
tensor([ 65., 271.]) tensor(False)
tensor([ 55., 261.]) tensor(False)
tensor([ 90., 338.]) tensor(False)
tensor([ 33., 195.]) tensor(True)
te

In [6]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[-0.3204, -0.2602],
        [-0.0918, -0.4856],
        [-0.0649, -0.2790],
        [-0.0685, -0.2613],
        [-0.5991,  0.1523],
        [ 0.1509,  0.2459],
        [ 0.6737, -0.2030],
        [-0.6868,  0.4532],
        [-0.1248, -0.4568],
        [ 0.5001,  0.4451],
        [-0.3503,  0.5246],
        [ 0.5580, -0.4144],
        [-0.4157,  0.2105],
        [-0.6595,  0.3027],
        [ 0.4124, -0.3477],
        [-0.2804, -0.3665],
        [-0.4160, -0.6704],
        [ 0.4100,  0.0912],
        [ 0.6549,  0.3666],
        [-0.6575, -0.5387],
        [-0.1849,  0.1088],
        [ 0.1167, -0.2496],
        [ 0.2218, -0.5686],
        [-0.3911,  0.3604],
        [-0.5699, -0.2218],
        [-0.1731,  0.5001],
        [ 0.0444, -0.1988],
        [-0.3349, -0.5277],
        [ 0.1303,  0.5284],
        [ 0.5984,  0.2512],
        [-0.3922, -0.5520],
        [ 0.6012, -0.5680],
        [-0.4101, -0.4505],
        [-0.4351, -0.4349],
        [ 0.1457,  0.0446]

In [7]:
np.zeros(32)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])